name: Build and Push Docker Images

on:
  workflow_run: # Trigger after successful CI
    workflows: ["Test Application"] # Name of your CI workflow
    types:
      - completed
    branches:
      - "**"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' # Only run if CI passed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: mistermre/all-in-one:backend-latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: mistermre/all-in-one:frontend-latest
